spring.application.name=EvolucaoParking
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/evolucao-parking
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
# Se o erro de coluna persistir, apague a pasta data/ e reinicie o servidor.
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.parking.total-vagas=20
app.parking.valor-fixo-24h=40.00
app.parking.tarifa-hora=5.00
app.parking.tolerancia-minutos=15
app.parking.bloco5h-valor=20.00
app.parking.bloco5h-horas=5
app.parking.bloco10h-valor=45.00
app.parking.bloco10h-horas=10
app.parking.excesso-bloco15min=2.00
